
    
services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    
    Thinkbig\Bundle\HivataliKapu\HivataliKapuBundle\Curl\Client:
        shared: false
        public: false
        arguments: 
            $url: "%hivatali_kapu.url%"

    Thinkbig\Bundle\HivataliKapu\HivataliKapuBundle\Curl\Request\Azonositas:
        public: true

    hivatali_kapu.azonositas:
        alias: Thinkbig\Bundle\HivataliKapu\HivataliKapuBundle\Curl\Request\Azonositas

    Thinkbig\Bundle\HivataliKapu\HivataliKapuBundle\Curl\Request\Viszontazonositas:
        public: true

    Thinkbig\Bundle\HivataliKapu\HivataliKapuBundle\Curl\Request:
        public: true

    Thinkbig\Bundle\HivataliKapu\HivataliKapuBundle\Curl\Request\HivatalokLekerdezese:
        public: true

    Thinkbig\Bundle\HivataliKapu\HivataliKapuBundle\Curl\Request\DokumentumokLekerdezeseGepiInterfeszAltal2:
        public: true

    hivatali_kapu.viszontazonositas:
        alias: Thinkbig\Bundle\HivataliKapu\HivataliKapuBundle\Curl\Request\Viszontazonositas

    Thinkbig\Bundle\HivataliKapu\HivataliKapuBundle\Curl\Request\TrKodEllenorzes:
        public: true
        arguments: ['@Thinkbig\Bundle\HivataliKapu\HivataliKapuBundle\Curl\Client', "BUK01", "BUK01", "YhEGV9wj"]

    Thinkbig\Bundle\HivataliKapu\HivataliKapuBundle\Curl\Request\UjDokumentumokFeltolteseGepiInterfeszAltal:
        public: true

    hivatali_kapu.dokumentumkuldes:
        alias: Thinkbig\Bundle\HivataliKapu\HivataliKapuBundle\Curl\Request\UjDokumentumokFeltolteseGepiInterfeszAltal
    
    Thinkbig\Bundle\HivataliKapu\HivataliKapuBundle\EventListener\HivataliKapuSubscriber:
        arguments: ["@monolog.logger.hivatali_kapu"]
        calls:
            - [setPath, ["%hivatali_kapu.resources_path%"]]
        tags:
            - {name: kernel.event_subscriber}
