
    
services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    
    BudapestBar\Bundle\HivataliKapu\HivataliKapuBundle\Curl\Client:
        shared: false
        public: false
        arguments: 
            $url: "%hivatali_kapu.url%"


    BudapestBar\Bundle\HivataliKapu\HivataliKapuBundle\Curl\Request\Azonositas:
        public: true

    BudapestBar\Bundle\HivataliKapu\HivataliKapuBundle\Curl\Request\Viszontazonositas:
        public: true

    BudapestBar\Bundle\HivataliKapu\HivataliKapuBundle\Curl\Request\TrKodEllenorzes:
        public: true
        arguments: ['@BudapestBar\Bundle\HivataliKapu\HivataliKapuBundle\Curl\Client', "BUK01", "BUK01", "YhEGV9wj"]

    BudapestBar\Bundle\HivataliKapu\HivataliKapuBundle\Curl\Request\UjDokumentumokFeltolteseGepiInterfeszAltal:
        public: true

    hivatali_kapu.dokumentumkuldes:
        alias: BudapestBar\Bundle\HivataliKapu\HivataliKapuBundle\Curl\Request\UjDokumentumokFeltolteseGepiInterfeszAltal
    
    BudapestBar\Bundle\HivataliKapu\HivataliKapuBundle\EventListener\HivataliKapuSubscriber:
        arguments: ["@monolog.logger.hivatali_kapu"]
        calls:
            - [setPath, ["%hivatali_kapu.resources_path%"]]
        tags:
            - {name: kernel.event_subscriber}
